trims:
  sentry: SPEED
  dune: STRENGTH
  coast: HASTE
  wild: NIGHT_VISION
  silence: HEALTH_BOOST
  rib: SPEED
  eye: NIGHT_VISION
  snout: STRENGTH
  tide: HASTE
  ward: HEALTH_BOOST
  spire: SPEED
  vex: HASTE
  wayfinder: NIGHT_VISION
  raiser: STRENGTH
  shaper: SPEED
  host: NIGHT_VISION
  dune: HASTE
  silence: HEALTH_BOOST
