name: Build TrimEffects (Paper 1.21)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B -q clean package

      - name: Upload Jar
        uses: actions/upload-artifact@v4
        with:
          name: TrimEffects
          path: target/*.jar
